/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ARGYLLE (https://sketchfab.com/argylle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/food-truck-ea0bfe0e409843c887dbf9f7a0634bfb
Title: FOOD TRUCK
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { foodTruck } from '../assets/3D'

export default function FoodTruck(props) {
  const { nodes, materials } = useGLTF(foodTruck)
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.424, 0]} scale={[9.781, 1.582, 3.9]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.TIRE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.YELLOW}
        />
      </group>
      <group
        position={[-1.522, 0.498, -0.435]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.04}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.headlight}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.blinkers}
        />
      </group>
      <group
        position={[-1.016, 0.868, 0.663]}
        rotation={[Math.PI, -0.703, -Math.PI / 2]}
        scale={[-0.044, 0.044, 0.044]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials.mirror}
        />
      </group>
      <group
        position={[-1.076, 0.215, 0.563]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.102}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_33.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_34.geometry}
          material={materials.TIRE}
        />
      </group>
      <group position={[0, 0.501, 0.24]} scale={0.299}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_42.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials.TIRE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_44.geometry}
          material={materials.BLUE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials.RED_DIAL}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_46.geometry}
          material={materials.anglebracket}
        />
      </group>
      <group position={[1.217, 0.845, 0.331]} scale={[0.095, 0.048, 0.171]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_50.geometry}
          material={materials.chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_51.geometry}
          material={materials.TIRE}
        />
      </group>
      <group
        position={[-1.001, 0.837, 0.352]}
        rotation={[-0.635, -0.162, -1.371]}
        scale={0.073}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_53.geometry}
          material={materials.TIRE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_54.geometry}
          material={materials.brown}
        />
      </group>
      <group
        position={[1.473, 0.222, 0.49]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.039}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_57.geometry}
          material={materials.blinkers}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58.geometry}
          material={materials.BRAKELIGHTS}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.wood}
        position={[0.698, 0.637, -0.59]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[-1, 1, 0.026]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.chrome}
        position={[-1.635, 0.479, -0.099]}
        rotation={[0.001, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.anglebracket}
        position={[1.243, 0.591, 0.64]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[-0.051, 0.06, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.chrome}
        position={[1.465, 1.346, -0.601]}
        scale={[0.027, 0.033, 0.012]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.chrome}
        position={[1.432, 0.433, 0.118]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.025}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.TIRE}
        position={[-1.058, 1.204, 0.319]}
        rotation={[0.419, -0.138, 1.386]}
        scale={[-0.01, 0.021, 0.021]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.chrome}
        position={[-0.448, 0.641, 0.545]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.036}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials.TIRE}
        position={[-1.076, 0.212, 0.476]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.215}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.YELLOW}
        position={[0.983, 1.671, 0.189]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.TIRE}
        position={[-0.508, 1.034, 0.273]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.04, 0.047, 0.074]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.brown}
        position={[-0.64, 0.373, 0.273]}
        scale={[0.201, 0.179, 0.189]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.chrome}
        position={[1.048, 0.501, 0.24]}
        scale={0.299}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials.rivets}
        position={[-0.968, 1.341, -0.593]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('/foodTruck.glb')
